Repository erpc/erpc, pull requests merged in 2024-07, with the labels that each got.

#10 feat: grafana charts
  monitoring/grafana/dashboards/erpc.json
Labels: enhancement

#11 feat: add docs based on nextra
  README.md
  common/config.go
  docs/.gitignore
  docs/Dockerfile
  docs/next-env.d.ts
  docs/next.config.mjs
  docs/package.json
  docs/pages/_meta.js
  docs/pages/config/_meta.js
  docs/pages/config/database.mdx
  docs/pages/config/example.mdx
  docs/pages/config/failsafe.mdx
  docs/pages/config/health-checks.mdx_
  docs/pages/config/projects.mdx
  docs/pages/config/projects/_meta.js
  docs/pages/config/projects/networks.mdx
  docs/pages/config/projects/upstreams.mdx
  docs/pages/config/rate-limiters.mdx
  docs/pages/deployment/docker.mdx_
  docs/pages/deployment/kubernetes.mdx_
  docs/pages/index.mdx
  docs/pages/operation/_meta.js_
  docs/pages/operation/monitoring.mdx_
  docs/pages/operation/production.mdx_
  docs/pages/operation/url.mdx_
  docs/pages/why.mdx
  docs/pnpm-lock.yaml
  docs/public/assets/hla-diagram.svg
  docs/public/assets/monitoring-example-erpc.png
  docs/railway.json
  docs/theme.config.tsx
  docs/tsconfig.json
  erpc.yaml.dist
  kube/erpc.yml
Labels: documentation

#7 feat: add llama vendor
  upstream/response.go
  vendors/llama.go
  vendors/registry.go
Labels: enhancement

#8 test: empty response retries and network tests
  cmd/erpc/main_test.go
  common/errors.go
  erpc/erpc.go
  erpc/evm_block_tracker.go
  erpc/evm_json_rpc_cache.go
  erpc/init.go
  erpc/networks.go
  erpc/networks_registry.go
  erpc/networks_test.go
  test/evm_json_rpc_test.go
  upstream/failsafe.go
  upstream/registry.go
  upstream/response.go
Labels: test

#12 feat: alchemy supported evm chains
  upstream/alchemy_http_json_rpc_client.go
Labels: enhancement

#18 feat: extending rpc json methods for caching
  erpc/evm_json_rpc_cache.go
  erpc/evm_json_rpc_cache_test.go
  evm/block_ref.go
  evm/block_ref_test.go
Labels: enhancement
