Repository erpc/erpc, pull requests merged in 2025-05, with the labels that each got.

#263 feat: add support for superchain provider
  common/defaults.go
  docs/pages/config/projects/providers.mdx
  thirdparty/superchain.go
  thirdparty/vendors_registry.go
Labels: enhancement

#273 chore: update prometheus configuration to include railway service endpoint
  monitoring/prometheus/prometheus.yml
Labels: bug

#284 chore: add AGENTS.md instructions
  AGENTS.md
Labels: codex

#310 feat: add a special provider to relay to a remote erpc instance
  common/defaults.go
  docs/pages/config/projects/providers.mdx
  erpc/evm_json_rpc_cache_test.go
  thirdparty/erpc.go
  thirdparty/vendors_registry.go
  typescript/config/lib/generated.d.ts
  typescript/config/lib/generated.d.ts.map
  typescript/config/lib/index.js.map
  typescript/config/lib/types/generic.d.ts
  typescript/config/src/generated.ts
  typescript/config/src/types/generic.ts
Labels: enhancement
